create table if not exists public.trip_plan_items (
  id bigint generated by default as identity primary key,
  trip_id text not null default 'hkmo-2026',
  traveler text not null
    check (traveler in ('traveler_a', 'traveler_b')),
  event_date date not null,
  event_time time,
  city text not null default '其他',
  title text not null,
  location text default '',
  note text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists trip_plan_items_trip_id_index
on public.trip_plan_items (trip_id);

create index if not exists trip_plan_items_date_index
on public.trip_plan_items (event_date, event_time);

alter table public.trip_plan_items
enable row level security;

grant usage on schema public
to anon, authenticated;

grant select, insert, update, delete
on table public.trip_plan_items
to anon, authenticated;

grant usage, select
on sequence public.trip_plan_items_id_seq
to anon, authenticated;

drop policy if exists "trip_plan_items_read_hkmo_2026"
on public.trip_plan_items;

create policy "trip_plan_items_read_hkmo_2026"
on public.trip_plan_items
for select
to anon, authenticated
using (trip_id = 'hkmo-2026');

drop policy if exists "trip_plan_items_insert_hkmo_2026"
on public.trip_plan_items;

create policy "trip_plan_items_insert_hkmo_2026"
on public.trip_plan_items
for insert
to anon, authenticated
with check (
  trip_id = 'hkmo-2026'
  and traveler in ('traveler_a', 'traveler_b')
);

drop policy if exists "trip_plan_items_update_hkmo_2026"
on public.trip_plan_items;

create policy "trip_plan_items_update_hkmo_2026"
on public.trip_plan_items
for update
to anon, authenticated
using (trip_id = 'hkmo-2026')
with check (
  trip_id = 'hkmo-2026'
  and traveler in ('traveler_a', 'traveler_b')
);

drop policy if exists "trip_plan_items_delete_hkmo_2026"
on public.trip_plan_items;

create policy "trip_plan_items_delete_hkmo_2026"
on public.trip_plan_items
for delete
to anon, authenticated
using (trip_id = 'hkmo-2026');

do $$
begin
  if exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'trip_plan_items'
  ) then
    alter publication supabase_realtime
    add table public.trip_plan_items;
  end if;
end $$;
